#@host = http://localhost:3000

POST {{host}}/register
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "john@example.com",
  "username": "john_doe1",
  "password": "secret password"
}

###
POST {{host}}/login
Content-Type: application/json

{
  "username": "john_doe1",
  "password": "secret password"
}
